spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true    # 이 설정 추가
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  sql:
    init:
      encoding: UTF-8
  security:
    enabled: false    

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG  # Security 로그도 추가
    org.springframework.http: TRACE
  file:
    name: ./logs/application.log  # 로그 파일 위치 지정
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"